#! /bin/bash
#   
# Service X Daemon 
#   
# chkconfig:    - 90 25  
# description:  Service X Daemon   


SERVICE_NAME='flume-monitor'
RUN_NAME='/data/www/install/flume-monitor'

SERVICE_START_CMD='...'
SERVICE_STOP_CMD='...'

. /etc/profile

acqPid() {
    local pid=`ps -ef |grep ${RUN_NAME}|grep -v grep |grep -v ${SERVICE_NAME}`
    test ".${pid}" != . && awk '{print $2}' <<< ${pid}
}

start () {
    echo -n $"Starting ${SERVICE_NAME}: "
    if [ ! -f /data/www/logs/apps/monitor/monitor.log ] ; then
        mkdir -p /data/www/logs/apps/monitor
        touch /data/www/logs/apps/monitor/monitor.log
        chown -R tomcat.tomcat /data/www/logs/apps/monitor
    fi
    if [ ".`acqPid`" == "." ] ; then
       cd /data/www/install/flume-monitor 
       /usr/bin/nohup \
       /data/www/install/flume-monitor/bin/flume-ng \
       agent -c /data/www/install/flume-monitor/conf -f /data/www/install/flume-monitor/conf/agent.properties -n agent -Dflume.monitoring.type=http -Dflume.monitoring.port=34545 \
       > /data/www/temp/flume-monitor.out 2>&1 &
    fi
    echo
}

stop () {
    echo -n $"Stopping ${SERVICE_NAME}: "
    if [ ".`acqPid`" == "." ] ; then
       echo "${SERVICE_NAME} not running!"
       exit 1 ;
    fi
    killall flume-ng
    RETVAL=$?
    if [ $RETVAL != 0 ] ; then
       kill -9 `acqPid`
    fi
    echo 
}

restart () {
    stop
    start
}


# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart|reload}"
    exit 1
esac

exit $?
