#!/bin/bash

function config(){

  ZABBIX_KEY="Day.Pay.Amount"

  SERVER_NAME=
  MYSQL_U=
  MYSQL_P=
  MYSQL_H=

  DEBUG_FILE_NAME=$(basename $0).log
  # 加载函数
  if [ -r "${PROMETHEUS_HOME}/funcs/funcs" ] ; then
     . ${PROMETHEUS_HOME}/funcs/funcs
  else
     echo "${PROMETHEUS_HOME}/funcs/funcs not found"
     exit 1 ;
  fi      

  # 加载statistic配置
  loadConf statistic.conf ;

}

function acqTimestamp(){
  local timestamp=$(date +%s)
  echo ${timestamp} 
}


function acqValue(){
local value=`/usr/local/mysql/bin/mysql -u${MYSQL_U} -p${MYSQL_P} -h ${MYSQL_H} << EOF 2>/dev/null
use sanguo;
select sum(amount) from payOrder where date(payTime) = curdate();
exit
EOF`
  value=`echo ${value} | awk '{print $2}'`
  [ "${value}" == "NULL" ] && exit 1;
  echo ${value}
}

function doStatistic(){
  local zabbix_value=`acqValue`
  if [ -n "${zabbix_value}" ] ; then
     #echo "${SERVER_NAME} ${ZABBIX_KEY} `acqTimestamp` ${zabbix_value}"
     echo "${SERVER_NAME} ${ZABBIX_KEY} `acqTimestamp` ${zabbix_value}" | /usr/local/zabbix/bin/zabbix_sender -T -vv -c /usr/local/zabbix/etc/zabbix_agentd.conf -i-
  fi
}

config ;
doStatistic ;
