#!/bin/bash

function config(){

  ZABBIX_KEY="Tomcat.Perf.Failed"

  SERVER_NAME="-"

  MONITOR_FILE="monitor.log"

  DEBUG_FILE_NAME=$(basename $0).log
  # 加载函数
  source /etc/profile
  test ".${PROMETHEUS_HOME}" = . && PROMETHEUS_HOME=/usr/local/prometheus
  if [ -r "${PROMETHEUS_HOME}/funcs/funcs" ] ; then
     . ${PROMETHEUS_HOME}/funcs/funcs
  else
     echo "${PROMETHEUS_HOME}/funcs/funcs not found"
     exit 1 ;
  fi      
  # 加载TOMCAT配置
  loadConf tomcat_setenv.conf ;
  # 加载statistic配置
  #loadConf statistic.conf ;
}

function acq_monitor_path(){
  local tomcatAppName=${TOMCAT_APP_NAME_OPT[0]}
  local tomcatHttpPort=`acqTomcatHttpPort ${tomcatAppName}`
  local appLogsPath=/data/www/logs/apps/${tomcatHttpPort}-${tomcatAppName}/app/${MONITOR_FILE}
  echo ${appLogsPath}
}

function acq_failed_max_cnt(){
  local appLogsPath=`acq_monitor_path`
  local i=0
  local maxValue=0
  for line in `tail -n 1 ${appLogsPath}` ; do
      i=$(( $i + 1 ))
      if [[ $i -ge 4 ]] ; then
         local key=`awk -F: '{print $1}' <<< ${line}`
         local values=`awk -F: '{print $NF}' <<< ${line}`
         test ".${values}" = . && continue
         # echo "key=${key}     values=$values"
         local value=`awk -F, '{print $4}' <<< ${values}`
         [ ${value} -gt ${maxValue} ] && maxValue=${value}
      fi
  done
  echo ${maxValue}
}


function acqTimestamp(){
  local timestamp=$(date +%s)
  echo ${timestamp} 
}


function acqValue(){
  local value=`acq_failed_max_cnt`
  echo ${value}
}

function doStatistic(){
  local zabbix_value=`acqValue`
  if [ -n "${zabbix_value}" ] ; then
     #echo "${SERVER_NAME} ${ZABBIX_KEY} `acqTimestamp` ${zabbix_value}"
     echo "${SERVER_NAME} ${ZABBIX_KEY} `acqTimestamp` ${zabbix_value}" | /usr/local/zabbix/bin/zabbix_sender -T -vv -c /usr/local/zabbix/etc/zabbix_agentd.conf -i-
  fi
}

config ;
#acq_failed_max_cnt ;
doStatistic ;
