#! /bin/bash
#   
# Service X Daemon 
#   
# chkconfig:    - 90 25  
# description:  Service X Daemon   

# 服务名称
SERVICE_NAME='ci'
# 进程字符串
RUN_NAME='atlassian-bamboo'

# 启动命令
SERVICE_START_CMD=/data/www/install/bamboo/bin/start-bamboo.sh
# 关闭命令
SERVICE_STOP_CMD=/data/www/install/bamboo/bin/stop-bamboo.sh

acqPid() {
    local pid=`ps -ef |grep ${RUN_NAME}|grep -v grep |grep -v ${SERVICE_NAME}`
    test ".${pid}" != . && awk '{print $2}' <<< ${pid}
}

start () {
    echo -n $"Starting ${SERVICE_NAME}: "
    if [ ".`acqPid`" == "." ] ; then
       ${SERVICE_START_CMD}
    fi
    echo
}

stop () {
    echo -n $"Stopping ${SERVICE_NAME}: "
    if [ ".`acqPid`" == "." ] ; then
       echo "${SERVICE_NAME} not running!"
       exit 1 ;
    fi
    ${SERVICE_STOP_CMD}
    RETVAL=$?
    if [ $RETVAL != 0 ] ; then
       kill -9 `acqPid`
    fi
    echo 
}

restart () {
    stop
    start
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart|reload}"
    exit 1
esac

exit $?